server.port=9099

spring.application.name=job_application_system_training_project

spring.datasource.url=jdbc:postgresql://localhost:5443/my_test_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.private.token=my_super_secret_key_123456_extra_characters_for_security

#logs
logging.level.org.springframework.security=DEBUG
logging.level.job_application_system_training_project=DEBUG

#1)
#docker run --name my-postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=my_test_db -p 5443:5432 -d postgres  ??? ?? ?????? ?? container
#
#2) docker exec -it my-postgres psql -U postgres -d my_test_db -c "\dt"  ??? ?? ?? ???????
#3)
#  ??????                                  ?? ?????
# docker stop my-postgres            ????????? ?? container
# docker start my-postgres           ???????? ?? container
# docker ps -a                       ????? ???? container ???????
# docker rm my-postgres              ?? ???????? ???????

#)4 ??? ??????? ??:
#docker exec -it my-postgres psql -U postgres -d my_test_db -c "ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(255);"

#5) ?? ???? ?? ???????? ??? ?????????? data ? ????????? data ???? ?? ??? table
#docker exec -it my-postgres psql -U postgres -d my_test_db -c "TRUNCATE TABLE users CASCADE;"


